-- =============================================
-- =============================================
--			Script Base Datos ORACLE		  --	
-- =============================================
-- =============================================
        
        CREATE TABLE tbl_Empleados 
        (
            CodigoEmpleado NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            Nombre VARCHAR2(100) NOT NULL,
            NumeroDpi NUMBER(19) NOT NULL,
            Genero CHAR(1) NOT NULL,
            Cargo VARCHAR2(50) NOT NULL,
            Salario NUMBER(10,2) NOT NULL,
            FechaNacimiento DATE NOT NULL,
            FechaContratacion DATE NOT NULL,
            Estado NUMBER(1) NOT NULL,
            UsuarioCreacion VARCHAR2(50),
            FechaCreacion DATE,
            UsuarioModificacion VARCHAR2(50),
            FechaModificacion DATE,
            UsuarioEliminacion VARCHAR2(50),
            FechaEliminacion DATE
        );
        
        CREATE TABLE tbl_Usuarios 
        (
            CodigoUsuario NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CodigoEmpleado NUMBER(10) NOT NULL,
            Correo VARCHAR2(100) NOT NULL,
            Usuario VARCHAR2(100) NOT NULL,
            Contrasenia VARCHAR2(100) NOT NULL,
            Rol VARCHAR2(100) NOT NULL,
            IntentosFallidos NUMBER(10),
            UltimoAcceso DATE,
            Estado NUMBER(1) NOT NULL,
            UsuarioCreacion VARCHAR2(50),
            FechaCreacion DATE,
            UsuarioModificacion VARCHAR2(50),
            FechaModificacion DATE,
            UsuarioEliminacion VARCHAR2(50),
            FechaEliminacion DATE,
            FOREIGN KEY (CodigoEmpleado) REFERENCES tbl_Empleados(CodigoEmpleado)
        );
        
        CREATE TABLE tbl_PlanillasEnc
        (
            CodigoPlanillaEnc NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            FechaPlanilla DATE NOT NULL,
            TipoPlanilla VARCHAR2(50) NOT NULL,
            Banco VARCHAR2(50),
            DocReferencia NUMBER(19),
            TipoMoneda CHAR(3) NOT NULL,
            MontoTotal NUMBER(10,2) NOT NULL,
            Observaciones VARCHAR2(255),
            Estado VARCHAR2(50) NOT NULL,
            UsuarioCreacion VARCHAR2(50),
            FechaCreacion DATE,
            UsuarioModificacion VARCHAR2(50),
            FechaModificacion DATE,
            UsuarioEliminacion VARCHAR2(50),
            FechaEliminacion DATE
        );
        
        CREATE TABLE tbl_PlanillasDet
        (
            CodigoPlanillaDet NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CodigoPlanillaEnc NUMBER(10) NOT NULL,
            CodigoEmpleado NUMBER(10) NOT NULL,
            SalarioBase NUMBER(10,2) NOT NULL,
            BonoLey NUMBER(10,2) NOT NULL,
            BonoExtra NUMBER(10,2),
            HorasExtras NUMBER(10),
            MontoHorasExtras NUMBER(10,2),
            Isr NUMBER(10,2),
            Igss NUMBER(10,2),
            MontoTotal NUMBER(10,2) NOT NULL,
            Estado NUMBER(1) NOT NULL,
            UsuarioCreacion VARCHAR2(50),
            FechaCreacion DATE,
            UsuarioModificacion VARCHAR2(50),
            FechaModificacion DATE,
            UsuarioEliminacion VARCHAR2(50),
            FechaEliminacion DATE,
            FOREIGN KEY (CodigoPlanillaEnc) REFERENCES tbl_PlanillasEnc(CodigoPlanillaEnc),
            FOREIGN KEY (CodigoEmpleado) REFERENCES tbl_Empleados(CodigoEmpleado)
        );
        
        CREATE TABLE tbl_Habitaciones (
            CodigoHabitacion NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            Numero VARCHAR2(10) NOT NULL,
            Ubicacion VARCHAR2(100),
            Tipo VARCHAR2(50) NOT NULL,
            PetFriendly NUMBER(1),
            CantidadHuesped NUMBER(10),
            Precio NUMBER(10,2) NOT NULL,
            PorcentajeAnticipo NUMBER(10,2),
            Estado NUMBER(1) NOT NULL,
            UsuarioCreacion VARCHAR2(50),
            FechaCreacion DATE,
            UsuarioModificacion VARCHAR2(50),
            FechaModificacion DATE,
            UsuarioEliminacion VARCHAR2(50),
            FechaEliminacion DATE
        );
        
        CREATE TABLE tbl_ServiciosHabitacion 
        (
            CodigoServicioHab NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CodigoEmpleado NUMBER(10) NOT NULL,
            CodigoHabitacion NUMBER(10) NOT NULL,
            TipoServicio VARCHAR2(50) NOT NULL,
            Turno CHAR(1) NOT NULL,
            FechaInicio DATE NOT NULL,
            FechaFin DATE NOT NULL,
            Observaciones VARCHAR2(255),
            Estado NUMBER(1) NOT NULL,
            UsuarioCreacion VARCHAR2(50),
            FechaCreacion DATE,
            UsuarioModificacion VARCHAR2(50),
            FechaModificacion DATE,
            UsuarioEliminacion VARCHAR2(50),
            FechaEliminacion DATE,
            FOREIGN KEY (CodigoEmpleado) REFERENCES tbl_Empleados(CodigoEmpleado),
            FOREIGN KEY (CodigoHabitacion) REFERENCES tbl_Habitaciones(CodigoHabitacion)
        );
        
        CREATE TABLE tbl_Huespedes
        (
            CodigoHuesped NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            Nombre VARCHAR2(100) NOT NULL,
            TipoIdentificacion VARCHAR2(50) NOT NULL,
            NumeroIdentificacion NUMBER(19) NOT NULL,
            FechaNacimiento DATE NOT NULL,
            Genero CHAR(1) NOT NULL,
            Telefono NUMBER(10),
            Direccion VARCHAR2(255),
            Puntuacion NUMBER(10,2),
            Estado NUMBER(1) NOT NULL,
            UsuarioCreacion VARCHAR2(50),
            FechaCreacion DATE,
            UsuarioModificacion VARCHAR2(50),
            FechaModificacion DATE,
            UsuarioEliminacion VARCHAR2(50),
            FechaEliminacion DATE
        );
        
        CREATE TABLE tbl_Hospedajes 
        (
            CodigoHospedaje NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CodigoHuesped NUMBER(10) NOT NULL,
            CodigoHabitacion NUMBER(10) NOT NULL,
            FechaIngreso DATE NOT NULL,
            FechaSalida DATE NOT NULL,
            MontoHabitacion NUMBER(10,2),
            MontoAnticipo NUMBER(10,2),
            MontoConsumos NUMBER(10,2),
            MontoTotal NUMBER(10,2) NOT NULL,
            Estado NUMBER(1) NOT NULL,
            UsuarioCreacion VARCHAR2(50),
            FechaCreacion DATE,
            UsuarioModificacion VARCHAR2(50),
            FechaModificacion DATE,
            UsuarioEliminacion VARCHAR2(50),
            FechaEliminacion DATE,
            FOREIGN KEY (CodigoHuesped) REFERENCES tbl_Huespedes(CodigoHuesped),
            FOREIGN KEY (CodigoHabitacion) REFERENCES tbl_Habitaciones(CodigoHabitacion)
        );
        
        CREATE TABLE tbl_Servicios 
        (
            CodigoServicio NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            Nombre VARCHAR2(100) NOT NULL,
            Tipo VARCHAR2(100) NOT NULL,
            Categoria VARCHAR2(100) NOT NULL,
            UnidadMedida VARCHAR2(20),
            PrecioUnitario NUMBER(10,2) NOT NULL,
            TiempoPreparacion NUMBER(10,2),
            Estado NUMBER(1) NOT NULL,
            UsuarioCreacion VARCHAR2(50),
            FechaCreacion DATE,
            UsuarioModificacion VARCHAR2(50),
            FechaModificacion DATE,
            UsuarioEliminacion VARCHAR2(50),
            FechaEliminacion DATE
        );
        
        CREATE TABLE tbl_ConsumosEnc 
        (
            CodigoConsumoEnc NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CodigoHospedaje NUMBER(10) NOT NULL,
            FechaConsumo DATE NOT NULL,
            MontoTotal NUMBER(10,2),
            Estado NUMBER(1) NOT NULL,
            UsuarioCreacion VARCHAR2(50),
            FechaCreacion DATE,
            UsuarioModificacion VARCHAR2(50),
            FechaModificacion DATE,
            UsuarioEliminacion VARCHAR2(50),
            FechaEliminacion DATE,
            FOREIGN KEY (CodigoHospedaje) REFERENCES tbl_Hospedajes(CodigoHospedaje)
        );
        
        CREATE TABLE tbl_ConsumosDet 
        (
            CodigoConsumoDet NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CodigoConsumoEnc NUMBER(10) NOT NULL,
            CodigoServicio NUMBER(10) NOT NULL,
            Cantidad NUMBER(10) NOT NULL,
            PrecioUnitario NUMBER(10,2) NOT NULL,
            PrecioTotal NUMBER(10,2) NOT NULL,
            MontoTotal NUMBER(10,2) NOT NULL,
            Observaciones VARCHAR2(255),
            Estado VARCHAR2(50),
            UsuarioCreacion VARCHAR2(50),
            FechaCreacion DATE,
            UsuarioModificacion VARCHAR2(50),
            FechaModificacion DATE,
            UsuarioEliminacion VARCHAR2(50),
            FechaEliminacion DATE,
            FOREIGN KEY (CodigoConsumoEnc) REFERENCES tbl_ConsumosEnc(CodigoConsumoEnc),
            FOREIGN KEY (CodigoServicio) REFERENCES tbl_Servicios(CodigoServicio)
        );
        
        CREATE TABLE tbl_Pagos (
            CodigoPago NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CodigoHospedaje NUMBER(10) NOT NULL,
            FechaPago DATE NOT NULL,
            MetodoPago VARCHAR2(100) NOT NULL,
            ReferenciaPago NUMBER(19),
            Monto NUMBER(10,2) NOT NULL,
            Propina NUMBER(10,2),
            Impuesto NUMBER(10,2),
            Descuento NUMBER(10,2),
            TotalPago NUMBER(10,2) NOT NULL,
            Estado NUMBER(1) NOT NULL,
            UsuarioCreacion VARCHAR2(50),
            FechaCreacion DATE,
            UsuarioModificacion VARCHAR2(50),
            FechaModificacion DATE,
            UsuarioEliminacion VARCHAR2(50),
            FechaEliminacion DATE,
            FOREIGN KEY (CodigoHospedaje) REFERENCES tbl_Hospedajes(CodigoHospedaje)
        );



-- =============================================
-- =============================================
--		Script Stored Procedure Try Catch     --	
-- =============================================
-- =============================================


		-- =============================================
		-- Author:		Elvis Morales
		-- Create date: 15/03/2026
		-- Description:	usp para agregar datos de la tabla huespedes 
		-- =============================================

			CREATE OR REPLACE PROCEDURE usp_AgregarHuespedes
				(
                    p_Nombre tbl_huespedes.Nombre%TYPE,
                    p_TipoIdentificacion tbl_huespedes.TipoIdentificacion%TYPE,
                    p_NumeroIdentificacion tbl_huespedes.NumeroIdentificacion%TYPE,
                    p_FechaNacimiento tbl_huespedes.FechaNacimiento%TYPE,
                    p_Genero tbl_huespedes.Genero%TYPE,
                    p_Telefono tbl_huespedes.Telefono%TYPE,
                    p_Direccion tbl_huespedes.Direccion%TYPE,
                    p_Puntuacion tbl_huespedes.Puntuacion%TYPE,
                    p_Estado tbl_huespedes.Estado%TYPE,
                    p_Resultado OUT NUMBER,
                    p_Mensaje OUT VARCHAR2                    
				)
			AS
			BEGIN
				Insert into Tbl_Huespedes
					(
					Nombre,
					TipoIdentificacion,
					NumeroIdentificacion,
					FechaNacimiento,
					Genero,
					Telefono,
					Direccion,
					Puntuacion,
					Estado
					)
				VALUES
					(
					p_Nombre,
					p_TipoIdentificacion,
					p_NumeroIdentificacion,
					p_FechaNacimiento,
					p_Genero,
					p_Telefono,
					p_Direccion,
					p_Puntuacion,
					p_Estado
					);   

                    p_Resultado := 1;
                    p_Mensaje := 'Huésped agregado correctamente Oracle';
                
                EXCEPTION
                    WHEN OTHERS THEN
                        p_Resultado := 0;
                        p_Mensaje := SQLERRM;                    

			END usp_AgregarHuespedes;  
            /
            
			-- Ejecutar Stored procedure

            SET SERVEROUTPUT ON;
            
            DECLARE
                v_resultado NUMBER;
                v_mensaje VARCHAR2(500);
            BEGIN
                usp_AgregarHuespedes(
                    'Elvis Morales',
                    'DPI',
                    124587896512,
                    '31-01-2026',
                    'O',
                    78888478,
                    'Cuilapa Santa Rosa',
                    5.5,
                    1,
                    v_resultado,
                    v_mensaje
                );
            
                DBMS_OUTPUT.PUT_LINE('Resultado: ' || v_resultado);
                DBMS_OUTPUT.PUT_LINE('Mensaje: ' || v_mensaje);
            END;
            /     
            
			-- Consultar Tabla

			Select * From tbl_Huespedes order by CodigoHuesped asc;
    
        
        -- =============================================
		-- Author:		Elvis Morales
		-- Create date: 15/03/2026
		-- Description:	Stored procedure para actualizar datos huespedes
		-- =============================================

            CREATE OR REPLACE PROCEDURE usp_EditarHuespedes
            (
                p_CodigoHuesped NUMBER,
                p_Nombre Tbl_Huespedes.Nombre%TYPE,
                p_TipoIdentificacion Tbl_Huespedes.TipoIdentificacion%TYPE,
                p_NumeroIdentificacion Tbl_Huespedes.NumeroIdentificacion%TYPE,
                p_FechaNacimiento Tbl_Huespedes.FechaNacimiento%TYPE,
                p_Genero Tbl_Huespedes.Genero%TYPE,
                p_Telefono Tbl_Huespedes.Telefono%TYPE,
                p_Direccion Tbl_Huespedes.Direccion%TYPE,
                p_Puntuacion Tbl_Huespedes.Puntuacion%TYPE,
                p_Estado Tbl_Huespedes.Estado%TYPE,
                p_Resultado OUT NUMBER,
                p_Mensaje OUT VARCHAR2
            )
            AS
            BEGIN
                UPDATE Tbl_Huespedes
                SET
                    Nombre = p_Nombre,
                    TipoIdentificacion = p_TipoIdentificacion,
                    NumeroIdentificacion = p_NumeroIdentificacion,
                    FechaNacimiento = p_FechaNacimiento,
                    Genero = p_Genero,
                    Telefono = p_Telefono,
                    Direccion = p_Direccion,
                    Puntuacion = p_Puntuacion,
                    Estado = p_Estado
                WHERE CodigoHuesped = p_CodigoHuesped;
            
                IF SQL%ROWCOUNT = 0 THEN
                    p_Resultado := 0;
                    p_Mensaje := 'No se encontró el huésped';
                ELSE
                    p_Resultado := 1;
                    p_Mensaje := 'Huésped actualizado correctamente Oracle';
                END IF;
            
            EXCEPTION
                WHEN OTHERS THEN
                    p_Resultado := 0;
                    p_Mensaje := SQLERRM;
            END;
            /      
            
			-- Ejecutar Stored procedure

            SET SERVEROUTPUT ON;
            
            DECLARE
                v_resultado NUMBER;
                v_mensaje VARCHAR2(500);
            BEGIN
                usp_EditarHuespedes(
                    1,
                    'Juan Perez',
                    'DPI',
                    1234567890101,
                    '22-02-2022',
                    'M',
                    55550000,
                    'Zona 1',
                    5.0,
                    1,
                    v_resultado,
                    v_mensaje
                );
            
                DBMS_OUTPUT.PUT_LINE('Resultado: ' || v_resultado);
                DBMS_OUTPUT.PUT_LINE('Mensaje: ' || v_mensaje);
            END;
            /

  			-- Consultar Tabla
            
            Select * From tbl_huespedes;    
        
    
		-- =============================================
		-- Author:		Elvis Morales
		-- Create date: 15/03/2026
		-- Description:	Stored procedure para eliminar datos huespedes
		-- =============================================
		-- =============================================

            CREATE OR REPLACE PROCEDURE usp_EliminarHuespedes
            (
                p_CodigoHuesped NUMBER,
                p_Resultado OUT NUMBER,
                p_Mensaje OUT VARCHAR2
            )
            AS
            BEGIN
                DELETE FROM Tbl_Huespedes
                WHERE CodigoHuesped = p_CodigoHuesped;
            
                IF SQL%ROWCOUNT = 0 THEN
                    p_Resultado := 0;
                    p_Mensaje := 'No se encontró el huésped';
                ELSE
                    p_Resultado := 1;
                    p_Mensaje := 'Huésped eliminado correctamente Oracle';
                END IF;
            
            EXCEPTION
                WHEN OTHERS THEN
                    p_Resultado := 0;
                    p_Mensaje := SQLERRM;
            END;
            /
            
			-- Ejecutar Stored procedure

            SET SERVEROUTPUT ON;
            
            DECLARE
                v_resultado NUMBER;
                v_mensaje VARCHAR2(500);
            BEGIN
                usp_EliminarHuespedes(1, v_resultado, v_mensaje);
            
                DBMS_OUTPUT.PUT_LINE('Resultado: ' || v_resultado);
                DBMS_OUTPUT.PUT_LINE('Mensaje: ' || v_mensaje);
            END;
            /

  			-- Consultar Tabla
            
            Select * From tbl_huespedes;       
    
                    
		-- =============================================
		-- Author:		Elvis Morales
		-- Create date: 15/03/2026
		-- Description:	usp para consultar datos de la tabla huespedes 
		-- =============================================

            CREATE OR REPLACE PROCEDURE usp_ConsultarHuespedes
            (
                p_cursor OUT SYS_REFCURSOR
            )
            AS
            BEGIN
                OPEN p_cursor FOR
                    SELECT *
                    FROM Tbl_Huespedes
                    ORDER BY CodigoHuesped;
            
            EXCEPTION
                WHEN OTHERS THEN
                    RAISE;
            END;
            /         

			-- Ejecutar Stored procedure

            VARIABLE rc REFCURSOR;
            
            EXEC usp_ConsultarHuespedes(:rc);
            
            PRINT rc;

  			-- Consultar Tabla
            
            Select * From tbl_huespedes;     
            
                     
		-- =============================================
		-- Author:		Elvis Morales
		-- Create date: 15/03/2026
		-- Description:	Stored procedure para buscar datos huespedes
		-- =============================================
		-- =============================================

            CREATE OR REPLACE PROCEDURE usp_BuscarHuespedes
            (
                p_Nombre VARCHAR2,
                p_cursor OUT SYS_REFCURSOR
            )
            AS
            BEGIN
                OPEN p_cursor FOR
                    SELECT *
                    FROM Tbl_Huespedes
                    WHERE Nombre LIKE '%' || p_Nombre || '%'
                    ORDER BY CodigoHuesped;
            
            EXCEPTION
                WHEN OTHERS THEN
                    RAISE;
            END;
            /
			-- Ejecutar Stored procedure

            VARIABLE rc REFCURSOR;
            
            EXEC usp_BuscarHuespedes('el', :rc);
            
            PRINT rc;

  			-- Consultar Tabla
            
            Select * From tbl_huespedes;    
            
            






-- =============================================
-- Author: Elmer De La Cruz
-- Create date: 15/03/2026
-- Description:	usp para agregar empleados (Corregido)
-- =============================================
CREATE OR REPLACE PROCEDURE usp_AgregarEmpleados
(
    p_Nombre            IN VARCHAR2,
    p_NumeroDpi         IN NUMBER, -- Usamos el tipo directo para evitar errores de declaración
    p_Genero            IN CHAR,
    p_Cargo             IN VARCHAR2,
    p_Salario           IN NUMBER,
    p_FechaNacimiento   IN DATE,
    p_FechaContratacion IN DATE,
    p_Estado            IN NUMBER,
    p_UsuarioCreacion   IN VARCHAR2,
    p_Resultado         OUT NUMBER,
    p_Mensaje           OUT VARCHAR2
)
AS
BEGIN
    INSERT INTO tbl_Empleados (
        Nombre, NumeroDpi, Genero, Cargo, Salario, 
        FechaNacimiento, FechaContratacion, Estado, 
        UsuarioCreacion, FechaCreacion
    ) VALUES (
        p_Nombre, p_NumeroDpi, p_Genero, p_Cargo, p_Salario, 
        p_FechaNacimiento, p_FechaContratacion, p_Estado, 
        p_UsuarioCreacion, SYSDATE
    );

    p_Resultado := 1;
    p_Mensaje := 'Empleado agregado correctamente Oracle';

EXCEPTION
    WHEN OTHERS THEN
        p_Resultado := 0;
        p_Mensaje := 'Error en Oracle: ' || SQLERRM;
END usp_AgregarEmpleados;
/

-- =============================================
-- Description: usp para consultar empleados
-- =============================================
CREATE OR REPLACE PROCEDURE usp_ConsultarEmpleados
(
    p_cursor OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_cursor FOR
        SELECT * FROM tbl_Empleados
        ORDER BY CodigoEmpleado;
END usp_ConsultarEmpleados;
/

-- =============================================
-- Description: usp para buscar empleados por nombre
-- =============================================
CREATE OR REPLACE PROCEDURE usp_BuscarEmpleados
(
    p_Nombre VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_cursor FOR
        SELECT * FROM tbl_Empleados
        WHERE UPPER(Nombre) LIKE '%' || UPPER(p_Nombre) || '%'
        ORDER BY CodigoEmpleado;
END usp_BuscarEmpleados;
/

-- =============================================
-- Description: usp para eliminar empleados
-- =============================================
CREATE OR REPLACE PROCEDURE usp_EliminarEmpleados
(
    p_CodigoEmpleado NUMBER,
    p_Resultado OUT NUMBER,
    p_Mensaje OUT VARCHAR2
)
AS
BEGIN
    DELETE FROM tbl_Empleados WHERE CodigoEmpleado = p_CodigoEmpleado;

    IF SQL%ROWCOUNT = 0 THEN
        p_Resultado := 0;
        p_Mensaje := 'No se encontró el empleado';
    ELSE
        p_Resultado := 1;
        p_Mensaje := 'Empleado eliminado correctamente';
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        p_Resultado := 0;
        p_Mensaje := SQLERRM;
END usp_EliminarEmpleados;
/
            
            
            